/** Picked once per page load. A fixed list for nowlater this can react to time of day or the weather itself. */
const GREETINGS = [
  "Welcome back!",
  "Hey.",
  "Good to see you.",
  "Hello again.",
  "Hi there.",
  "Hey there.",
  "Welcome.",
  "Nice to see you.",
  "Hello, friend.",
  "Hey, you.",
  "Look who it is.",
  "Missed you.",
  "Glad you're here.",
  "You're back.",
  "Right on time.",
  "Here we go.",
  "Let's do this.",
  "Fresh tab, fresh start.",
  "Onward.",
  "Ready when you are.",
  "All set.",
  "Back at it.",
  "Rise and shine.",
  "Another one.",
  "Good timing.",
  "Home base.",
  "Making moves.",
  "One more time.",
  "Off we go.",
  "Good to have you.",
  "Hey again.",
  "Well, hello.",
  "Right this way.",
  "Let's begin.",
  "Good morning, sort of.",
  "Systems go.",
  "All systems go.",
  "Booting up.",
  "Refreshed and ready.",
  "New tab, who dis?",
  "404: boredom not found.",
  "No merge conflicts here.",
  "Build's green.",
  "Zero bugs, for now.",
  "Running smoothly.",
  "Uptime: good.",
  "Syncing up.",
  "Terminal's open.",
  "Let's ship it.",
  "Committed to today.",
]

export function randomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)]
}
